services:
  budgeteer:
    image: budgeteer:latest
    container_name: budgeteer
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/budgeteerdb
      SPRING_DATASOURCE_USERNAME: budgeteeruser
      SPRING_DATASOURCE_PASSWORD: budgeteerpassword
    depends_on:
      - postgres
    networks:
      - monitoring

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: budgeteerdb
      POSTGRES_USER: budgeteeruser
      POSTGRES_PASSWORD: budgeteerpassword
    ports:
      - "5432:5432"
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/proc'
      - '--path.sysfs=/sys'
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /proc:/host/proc
      - /sys:/host/sys
    ports:
      - "9090:9090"
    depends_on:
      - node_exporter
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring: