version: '3.8'

services:
  budgeteer:
    image: budgeteer:latest
    container_name: budgeteer
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/budgeteerdb
      SPRING_DATASOURCE_USERNAME: budgeteeruser
      SPRING_DATASOURCE_PASSWORD: budgeteerpassword
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: budgeteerdb
      POSTGRES_USER: budgeteeruser
      POSTGRES_PASSWORD: budgeteerpassword
    ports:
      - "5432:5432"
